version: "3.8"

services:
  rahoot:
    image: ghcr.io/vonjunge/rahoot:latest
    ports:
      - "3000:3000"
      - "3001:3001"
    volumes:
      - ./config:/app/config # Path to your game config
    environment:
      - WEB_ORIGIN=http://localhost:3000
      - SOCKET_URL=http://localhost:3001
      - MANAGER_PASSWORD=PASSWORD # Set your manager password here
      - BACKGROUND_IMAGE_URL= # Optional: Set custom background image URL
